### PR TITLE
Fix Missing Directory Issue for Installation

### PR DESCRIPTION
**Pull request by fullmetalcache**
This PR moves the check for $Env:programfiles\Sysmon towards the top of the code before anything tries to use that directory.

### CODE REVIEW

**Review by Zalgo2462 — APPROVED** [review]
LGTM.

**Comment by fullmetalcache** [comment]
Sorry, I commented on this in the issue rather than the PR. Directory issue seems resolved but getting this at the end. Stand by for fix

image

**Comment by Zalgo2462** [comment]
Standing by. :+1:

**Comment by Zalgo2462** [comment]
Tested fresh installation as well as upgrade. LGTM

**Pull request merged**
